#!/bin/bash
# Quick installation guide for HA VMI Addon

echo "╔════════════════════════════════════════════════════════════╗"
echo "║   HA VMI - Home Assistant Addon Installation Guide        ║"
echo "║   Migration from Jeedom Openenocean + Ventilairsec        ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Check if running in Home Assistant
if [ ! -f "/.dockerenv" ]; then
    echo "⚠️  Warning: This script should be run inside Home Assistant"
    echo ""
fi

echo "📋 Installation Checklist:"
echo ""

echo "✅ Step 1: Prepare Home Assistant"
echo "   [ ] Ensure Home Assistant is running"
echo "   [ ] Ensure MQTT Broker is installed (Mosquitto addon)"
echo "   [ ] Configure MQTT integration in Home Assistant"
echo "   [ ] Note: Settings → Integrations → MQTT"
echo ""

echo "✅ Step 2: Add Repository (if not pre-installed)"
echo "   [ ] Go to: Settings → Add-ons → Add-on Store"
echo "   [ ] Click menu (⋮) → Repositories"
echo "   [ ] Add: https://github.com/fortinric88/VMI"
echo "   [ ] Click Create"
echo ""

echo "✅ Step 3: Install HA VMI Addon"
echo "   [ ] Go to: Add-on Store"
echo "   [ ] Search for: 'HA VMI' or 'VMI Ventilairsec'"
echo "   [ ] Click Install"
echo ""

echo "✅ Step 4: Configure Addon"
echo "   [ ] Go to: Settings → Add-ons → HA VMI"
echo "   [ ] Click Configuration"
echo "   [ ] Fill required fields:"
echo "       - device: auto (or /dev/ttyUSB0)"
echo "       - log_level: info"
echo "       - mqtt_broker: localhost"
echo "       - mqtt_port: 1883"
echo "       - mqtt_user: (leave empty if local)"
echo "       - mqtt_password: (leave empty if local)"
echo "       - vmi_name: Ventilairsec"
echo "   [ ] Click Save"
echo ""

echo "✅ Step 5: Start Addon"
echo "   [ ] Go to: Settings → Add-ons → HA VMI"
echo "   [ ] Click Start"
echo "   [ ] Wait 5-10 seconds"
echo "   [ ] Click Logs to verify startup"
echo "   [ ] Look for: 'All services started successfully'"
echo ""

echo "✅ Step 6: Verify MQTT Communication"
echo "   [ ] Use a MQTT client (MQTT Explorer or mosquitto_sub)"
echo "   [ ] Subscribe to: home/vmi/#"
echo "   [ ] Should see messages from the addon"
echo ""

echo "✅ Step 7: Wait for Entities"
echo "   [ ] Go to: Developer Tools → States"
echo "   [ ] Filter by: sensor.ventilairsec_"
echo "   [ ] Should see 50+ entities"
echo "   [ ] If not, wait 30 seconds and refresh"
echo ""

echo "✅ Step 8: Create Dashboard"
echo "   [ ] Go to: Lovelace Dashboard"
echo "   [ ] Create new card with VMI entities"
echo "   [ ] Or use template from HOMEASSISTANT_INTEGRATION.md"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "🔧 Troubleshooting Quick Links:"
echo "   • Addon won't start → Check MQTT broker is running"
echo "   • No MQTT messages → Check configuration (mqtt_broker)"
echo "   • No entities → Restart Home Assistant"
echo "   • Dongle not found → Run: ls /dev/ttyUSB* and use exact path"
echo ""

echo "📚 Documentation Files:"
echo "   • README.md - Quick start guide"
echo "   • CONFIGURATION.md - All configuration options"
echo "   • HOMEASSISTANT_INTEGRATION.md - HA integration guide"
echo "   • MQTT_ARCHITECTURE.md - MQTT topic structure"
echo "   • MIGRATION_GUIDE.md - Full migration overview"
echo ""

echo "🌐 Useful URLs:"
echo "   • Home Assistant: http://homeassistant.local:8123"
echo "   • MQTT Explorer: (download from https://mqtt-explorer.com/)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "👉 Next Steps:"
echo "   1. Follow the checklist above"
echo "   2. Install the addon in Home Assistant"
echo "   3. Configure with your MQTT broker settings"
echo "   4. Start the addon and verify in logs"
echo "   5. Create automations and dashboards"
echo ""
echo "📞 Having trouble? Check the documentation or GitHub issues:"
echo "   https://github.com/fortinric88/VMI/issues"
echo ""
echo "✨ Happy automating with your VMI!"
echo ""
